### PR TITLE
Fix duplicated packages when updating environment

### PR DESCRIPTION
**Pull request by gqmelo**
When updating an environment, the currently installed packages were not
being considered, so new versions of packages were installed without
uninstalling old versions.

### CODE REVIEW

**Comment by gqmelo** [comment]
Just a note: `test_create.py` was based on conda's `test_create.py`

**Comment by mbargull** [comment]
To my knowledge the conda-env repository is deprecated and `conda-env` is now part of [conda](https://github.com/conda/conda-env).
I guess you would rather have to issue a PR for that repository.

**Comment by gqmelo** [comment]
@ma-ba, thank you! I heard there was an intention to merge the two projects, but didn't know it already happened, I'll see if I can find time to make the fix in the new version

**Comment by gqmelo** [comment]
@kalefranz, what should be done about this PR? Should I close it and re-submit to the `conda` repo?

**Comment by gqmelo** [comment]
Fixed on conda repository

**Pull request closed without merging**
