### PR TITLE
PROMPT environment variable is being reset to $P$G by activate.bat

### PR DESCRIPTION
**Pull request by tadeu**
PROMPT was being reset to "$P$G" on activate, ignoring user customizations. This change fixes this.

### CODE REVIEW

**Comment by nicoddemus** [comment]
:+1:

**Comment by malev** [comment]
@nicoddemus did you test this? in what platforms?

**Comment by tadeu** [comment]
@malev I manually tested it in Windows 7, but I couldn't find unit tests for `activate` to make a new test... do you need unit tests for this? I think that appveyor is not working for conda-env too, right?

**Comment by msarahan** [comment]
This is (probably) fixed in https://github.com/conda/conda/pull/1727

We'll work on this again once we get the Anaconda 2.4.1 release out.

**Comment by msarahan** [comment]
Sorry, not paying enough attention.  This is a good intermediate patch until https://github.com/conda/conda/pull/1727 replaces it.  +1 from me.

**Comment by malev** [comment]
@msarahan when is anaconda 2.4.1 gonna be released? What's gonna happen with this fix once 2.4.1 has been released?
@tadeu I just wanted to know where have you tested. We don't have unit tests for this. No big deal

**Comment by msarahan** [comment]
Beginning of December.  Once 2.4.1 is released, I want to push that PR to completion, as it makes the activation scripts unit testable on Windows, and also adds conda activate support for MSys/Cygwin on Windows.  That PR already contains functionality similar to this PR (restoring existing prompt, rather than forcing $P$G).

**Comment by tadeu** [comment]
:+1:

**Comment by malev** [comment]
Sounds great @msarahan I'd love to release conda-env next week.

**Comment by msarahan** [comment]
Thanks!

**Pull request merged**
