### PR TITLE
Set CONDA_ENV_PATH environmental variable to active env root path

### PR DESCRIPTION
**Pull request by tdhopper**
As discussed in [this issue](https://github.com/conda/conda-env/issues/63)

### CODE REVIEW

**Comment by tswicegood** [comment]
Sorry for the delay -- this looks good to me.  Merging and will release with the next release.  Thanks for the contribution! :+1:

**Comment by tacaswell** [comment]
Thanks :beers:

**Comment by tswicegood** [comment]
Unless someone really needs this, I'm going to not release it until Monday.  We've got PR #73 which should be merged then and I'll release it then.

**Comment by tacaswell** [comment]
I do not need it over the weekend (and if I did I would just build my own package).

**Pull request merged**
