### PR TITLE
Undo -n deprecation

### PR DESCRIPTION
**Pull request by malev**
Working on #105

### CODE REVIEW

**Comment by tswicegood** [comment]
Just reviewed from my phone, but this still deprecates --name in favor of the name without the opts but removes the message saying that. 

The original idea behind deprecating --name is that it should still work but display the warning message so that at some point it could be completely removed in the future when BC can be broken.

**Comment by malev** [comment]
I'm not sure how do we should fix this. I'm feeling like deprecating `-n` wasn't the greatest idea. Maybe we should keep it the way it was and add a new flag for the `remote_definitions` as in:
```sh
$ conda env create --help
usage: conda-env create [-h] [-f FILE] [-n NAME] [-q] [--json]
                        [remote_definition]

positional arguments:
  remote_definition     remote environment definition

optional arguments:
  -n NAME, --name NAME  environment definition

examples:
    conda env create
    conda env create -n name
    conda env create vader/deathstar
    conda env create -f=/path/to/environment.yml
```
What do you think?

**Comment by tswicegood** [comment]
I'm still -1 on `-n` as its weird to type `conda foo -n bar -y`.  That said, I can see a case where you need them both so maybe it's ok to keep around.

**Comment by malev** [comment]
Agree with the weirdness but that's the way conda works in general, it's gonna be weirder to have conda using `-n` and conda-env not using it.

**Comment by tswicegood** [comment]
Yeah -- my eventual hope was to deprecate/remove it there too, but I doubt that'll happen now. :-(

**Comment by malev** [comment]
I still believe that:
`conda env create malev/stats-env` is the way to go!
And now it feels like we can also do:
`conda env create malev/stats-env -n new-env-name` and that seems to be pretty useful for of our users.

**Comment by joelhullcio** [comment]
@tswicegood -n is a well established parameter across anaconda.  IF it is deprecated it should be deprecated in unison across all of conda for consistency.  I see your point on "weirdness" but it may be a premature optimization at this point.  Please just return the functionality to the previous state without deprecation.  Add other parameters to handle any new or special remote features.  Thanks.

**Comment by tswicegood** [comment]
LGGT :+1:

**Comment by eriknw** [comment]
I am very confused by this thread.

It appears you want to specify a remote environment definition obtained, by default, from anaconda.org.  Moreover, this is done from the *positional* argument.  I would expect arguments that specify remote resources to be explicitly called out, such as `conda env create -r malev/stats-env`.  The exception to this would be if the conda sub-command were something like `conda remote` or `conda env clone`.

What would most users expect the positional argument to `conda env create` do: (1) specify an environment yaml file, (2) new conda environment name, (3) remote conda name to install locally, or (4) some combination of these three?

I expect it to specify a conda environment definition.  Perhaps the positional argument can specify a local environment yaml file *or* a remote `{channel}/{envname}`.  Note that this is different from the original (broken) deprecation behavior, which said one could specify the new environment name as the positional argument.

To be clear, I think sharing environments via anaconda.org is an awesome feature to support.

**Comment by malev** [comment]
@eriknw,
1) I'm gonna guess that `-f` flag exists because `conda` has a `-f` flag and make sense to have reproduce that here as well
2) yes! I agree and I think it's cool but as @joelhullcio pointed out "-n is a well established parameter across anaconda"
3) maybe! My inspiration on this was `git clone`. The original discussion is in https://github.com/conda/conda-env/pull/73
4) Good luck with this one!! Not simple to implement

All that said, I'm gonna merge this now because there is people missing this feature. We can continue this debate in an issue.

**Comment by eriknw** [comment]
I remain somewhat confused, and I think usage of `conda env create` is unnecessarily complicated by kludging remote functionality into it.  I don't understand why (4) would not be simple to implement.

Thanks for adding `--name` functionality back--and not deprecating it--to override the new environment name.

**Pull request merged**
