### PR TITLE
Using Jupyter 4.0

### PR DESCRIPTION
**Pull request by malev**

### CODE REVIEW

**Comment by ccordoba12** [comment]
@malev, I couldn't help to notice that you changed `ipython` for `jupyter` in this PR. But if conda-env depends only on the notebook part of Jupyter, I think you should just use the new `notebook` package instead of `jupyter`.

The thing is `jupyter` is a metapackage which installs not only the notebook but also the `qtconsole` and `console` frontends, which it seems you really don't need in this case :-)

**Comment by malev** [comment]
@ccordoba12 `jupyter` is an optional dependency from conda-env, you don't need it at first glance. You only need `jupyter` when you are dealing with notebooks. If that's the case it's very possible that you will have jupyter already installed.

**Comment by ccordoba12** [comment]
Ok, I didn't know that. But my suggestion was for `conda-env` to (optionally) depend *directly* on the `notebook` package instead of on `jupyter`.

I mean, the idea of Jupyter is not only to rename IPython to reflect its language agnostic nature, but also to allow a more fine-grained control over its multiple components.

For example, Spyder will depend (from now on) on the `qtconsole` package because that's the only Jupyter frontend that we currently use. The `jupyter` package brings several other components (like the notebook) that we don't really need :-)

**Comment by damianavila** [comment]
:+1: to @ccordoba12 commets...

**Pull request merged**
