### PR TITLE
Bring activate / deactivate into this

### PR DESCRIPTION
**Pull request by tswicegood**
Should be released before conda removes them, but we eventually need to remove it from conda as well.

### CODE REVIEW

**Comment by tswicegood** [comment]
Note, I'm going to merge this to `develop` before merging to `master`, just opened the PR against the wrong branch.

**Comment by tswicegood** [comment]
@ilanschnell I'm blocked on this because of binstar-build.  Can you test that it works and that conda's tests continue to pass on Windows with this installed?

**Comment by ilanschnell** [comment]
Seems to work.  The `activate.bat` and `deactivate.bat` are exactly what is currently in conda.

**Comment by tswicegood** [comment]
@ilanschnell thank you for testing for me.  I just pushed 8d5e383d9af2a5eacb627e0903255cc4501232b6 to this branch that fixes a bug when you have an empty `$PREFIX/etc/conda/activate.d/` directory.  That change needs to be available in conda as well or the bug (non-critical, it's just extra output) is present.

Let's go ahead and roll the v2.1.0 release of conda-env and then remove `activate` and `deactivate` from `conda`.  Do you want to do that today or wait until Monday?

**Pull request merged**
