### PR TITLE
remove selectors

### PR DESCRIPTION
**Pull request by kalefranz**
@mcg1969 I win.

### CODE REVIEW

**Comment by Korijn** [comment]
Well, this is unexpected! Might I ask why? 

I contributed this code and invested a lot of effort into this. If there's any issues that you are experiencing I'd love to see if there is an alternative solution to just ripping it out...

**Comment by kalefranz** [comment]
CC @pzwang

**Comment by pzwang** [comment]
Yep, please discussion offline.

**Comment by kalefranz** [comment]
@Korijn sent an email to your gmail address.  Happy to discuss further.

**Comment by ocefpaf** [comment]
@kalefranz I just found this and I am curious why this was removed too. I understand that having selectors in the `environment.yml` can lead to poor reproducibility as envs are not guaranteed to be the same under different platforms. However, it would be nice to be able to add some platform specific packages in envs that are not really related to the reproducibility. For example, adding `console_shortcut` for Windows envs.

**Pull request merged**
