### PR TITLE
rewrite activate.bat and deactivate.bat on win

### PR DESCRIPTION
**Pull request by msarahan**
This is the same script in spirit, but not in body.  I have rewritten it to use subroutines instead of gotos quite as much (subtle difference, but a big one.)

@ukoethe @ccordoba12 @groutr @wulmer @remram44 @malev , as people who have contributed towards this script in the past or are otherwise involved, please review and ensure that it maintains your functionality.  It would have been nicer to integrate the @wulmer PR: https://github.com/conda/conda-env/pull/182, but I don't want to have to change conda right now, as is required therein.  That will be in the next release.

I have tested this interactively only.  I am writing python-driven tests for this now, but anticipate that this will take me some time to figure out.  I don't know yet how to test what environment I'm on, and I need to work out the subprocess calls and output parsing.

I expect that this PR will not be merged without automated tests in tow, but I would appreciate any comments you have before then.

### CODE REVIEW

**Comment by msarahan** [comment]
One issue right off the bat: I renamed CONDA_DEFAULT_ENV to CONDA_ACTIVE_ENV to be more descriptive.  I see now that CONDA_DEFAULT_ENV is used elsewhere in Conda.  I will rename it here to match that usage, to avoid further headache.

**Comment by msarahan** [comment]
Ping @mikecroucher, you had a hand in this as well. Sorry I missed you on the earlier list.

**Comment by msarahan** [comment]
Just noticed: this is setting the cute little prompt thing, but not setting PATH properly.

**Comment by msarahan** [comment]
This is all a terrible idea.  Easier to just integrate #182 and https://github.com/conda/conda/pull/1707 .  @wulmer did a lot of nice work, and has tests there.  I am going to merge that and figure out what features might be missing there (activating by absolute/relative path?)

Thanks, if anyone has looked at this.  I've had enough fun with bat files.

**Comment by ukoethe** [comment]
> One issue right off the bat: I renamed CONDA_DEFAULT_ENV to CONDA_ACTIVE_ENV to be more descriptive. I see now that CONDA_DEFAULT_ENV is used elsewhere in Conda. I will rename it here to match that usage, to avoid further headache.

In the long run, I like `CONDA_ACTIVE_ENV` much better. I'd be perfectly willing to change https://github.com/conda/conda-build/pull/578 accordingly -- in fact, it will be much easier to change now than later.

**Comment by ukoethe** [comment]
I did a quick search over `conda`, `conda-env`, and `conda-build` and didn't find many places where `CONDA_DEFAULT_ENV` is used. From that perspective, it is no problem to change the name. Are there many recipes that rely on that variable name?

**Pull request closed without merging**
