### PR TITLE
Just let conda/cli/main_remove do the remove work

### PR DESCRIPTION
**Pull request by mcg1969**
Even better than #250. Just forward `conda env remove` along to the `conda remove --all` logic.

### CODE REVIEW

**Comment by Korijn** [comment]
Is there a unit test for this logic?

**Comment by mcg1969** [comment]
We do exercise `conda remove` in integration testing...

**Comment by mcg1969** [comment]
I'm not familiar with the `conda-env` test suite but a cursory look suggests that `conda env remove` is not exercised, even before this PR.

**Comment by Korijn** [comment]
Ok! There is another code path `conda env create --force` that removes an environment (using `conda.install.rm_rf`) if it exists before creating it anew. It's currently broken (at least on Windows), and by hooking it up to this code it would probably be fixed. Would you consider including that change in this PR? It should be fairly simple.

**Comment by mcg1969** [comment]
I'm not sure you can do that here, since that requires a less interactive result.

**Comment by Korijn** [comment]
You could pass `yes: True` and possibly `quiet: True` as well along in that case to bypass interactivity, perhaps?

**Comment by mcg1969** [comment]
That certainly seems reasonable but I must defer to the primary conda-env maintainer here. I think I would rather see `rm_rf` fixed, however, because it is used elsewhere in `conda`.

**Comment by Korijn** [comment]
Cc @msaharan @kalefranz ?

**Comment by mcg1969** [comment]
No need to ping them. They will both be looking at this soon. You and I have been having a conversation in the middle of the night / early morning our time.

**Comment by Korijn** [comment]
Oh, OK! Sorry, I'm not really aware of the structure of your team etc. :)

**Comment by mcg1969** [comment]
Oh, no problem! Yesterday was a very eventful day for us all, so I have no doubt they're getting some much-needed sleep :-)

**Comment by kalefranz** [comment]
This one.

**Pull request merged**
