### PR TITLE
Feature/export channels

### PR DESCRIPTION
**Pull request by malev**
### Why?
When exporting channels information is missing:
`conda env export -n root`
```yaml
name: root
dependencies:
- binstar=0.11.0=py27_0
- certifi=14.05.14=py27_0
```
The environment.yaml file can't be used because it lack on the source of the packages (channels).

### Solution
Include channels (listed on `.condarc`) custom channels (`-c` flag):
`conda env export -c binstar --override-channels -n root`
```yaml
name: root
channels:
- binstar
dependencies:
- binstar=0.11.0=py27_0
- certifi=14.05.14=py27_0
```

There is an open bug talking about this as well #97

### CODE REVIEW

**Comment by tswicegood** [comment]
You might want to talk with @chdoig about this a bit as she's one of the one's who's asked for this.  I believe the desired behavior here isn't explicitly setting channels at export time so much as gather the channels from Conda's metadata when exporting so you don't have to remember that channel `foobar` was used.

FWIW, the data you need is in the `{{ path to env }}/conda-meta/{{ package }}-{{ version }}-{{ build }}.json` file under `channel` if it exists.  To my knowledge there is no API for getting that data and no official documentation of what goes into that file.

**Comment by malev** [comment]
* Didn't know about `conda-meta` it's great!
* I agree with you but I also believe this is a step towards reproducibility of environments.
* I don't want to make a broader change into `conda-env`. Not sure if we can include all that information into the `environment.yaml` file and how is the `conda env create` will respond to that. I saw this as an easy temporally fix
* In the near future I'd like to have namespaces into the `environment.yaml` file, something like:
```yaml
dependencies:
- javascript/nodejs
- javascript/bower
- binstar=0.11.0
```
And `conda-env create` will go to that particular channel to look for the package.

**Comment by tswicegood** [comment]
+1 for the channel-specific package specification.  I know @asmeurer has given it some thought, but I don't know if anything's every been done on it.

**Comment by msarahan** [comment]
Ping @malev can you revisit this and reassure me that it's ready?  I'll merge if you say it's good.

**Comment by rain1024** [comment]
This is really helpful feature. Please merge it soon.

**Pull request merged**
