### PR TITLE
Fix CONDA_ENV_PATH

### LINKED ISSUE #82: BUG: CONDA_ENV_PATH does not behave as expected
If I understand the intent of #80, `$CONDA_ENV_PATH` should point the "root" directory of the currently-activated environment. As implemented, it always points to the root miniconda directory.

With conda-env master installed in my root environment...

```
$ conda update conda-env
Fetching package metadata: ........
# All requested packages already installed.
# packages in environment at /home/dallan/mc:
#
conda-env                 2.2alpha.0      py27_16_ga964ad9  
```

...I create a new environment...

```
$ conda create -n test-envs python
Fetching package metadata: ........
Solving package specifications: .
Package plan for installation in environment /home/dallan/mc/envs/test-envs:

The following NEW packages will be INSTALLED:

    ncurses:    5.9-6       
    openssl:    1.0.1k-1    
    pip:        6.1.1-py27_0
    python:     2.7.9-10    
    readline:   6.2-12      
    setuptools: 15.2-py27_0 
    sqlite:     3.8.4.1-1   
    system:     5.8-2       
    tk:         8.5.18-0    
    zlib:       1.2.8-0     

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##########################################################################| 100%
#
# To activate this environment, use:
# $ source activate test-envs
#
# To deactivate this environment, use:
# $ source deactivate
#
```

...activate it...

```
$ source activate test-envs
discarding /home/dallan/mc/bin from PATH
prepending /home/dallan/mc/envs/test-envs/bin to PATH
```

...and for the environmental variable to be not what I expect:

```
$ echo $CONDA_ENV_PATH
/home/dallan/mc
```

### PR DESCRIPTION
**Pull request by campos-ddc**
Fixes #82

### CODE REVIEW

**Comment by tswicegood** [comment]
:+1: in general.  I think there might be a utility CLI command that would let you do this without the `awk` command.  @ilanschnell @asmeurer -- is there a way to get the prefix for an environment?

**Comment by quasiben** [comment]
This won't work on windows, correct?

**Comment by campos-ddc** [comment]
@quasiben This change should not affect Windows at all, there is an `activate.bat` file for it.

Though I did not test `CONDA_ENV_PATH` in Windows, it looks like it is working just from reading that `.bat`.

**Comment by tdhopper** [comment]
What's happening here @campos-ddc, @tswicegood? This would be a big help to me.

**Comment by tdhopper** [comment]
Oh. @tswicegood left continuum. @campos-ddc can you fix the merge conflict?

**Comment by malev** [comment]
@campos-ddc it doesn't seem to be working in linux:
```
root@01eb2edc87c8:~/conda-env# echo $CONDA_ENV_PATH

root@01eb2edc87c8:~/conda-env# source activate temp
discarding /root/miniconda/bin from PATH
prepending /root/miniconda/envs/temp/bin to PATH
(temp)root@01eb2edc87c8:~/conda-env# echo $CONDA_ENV_PATH
/root/miniconda
(temp)root@01eb2edc87c8:~/conda-env# git branch
  develop
* fix-CONDA_ENV_PATH
(temp)root@01eb2edc87c8:~/conda-env#
```

**Comment by campos-ddc** [comment]
Hm, I'll take a look at it soon (on vacations right now)

**Comment by malev** [comment]
@campos-ddc have fun!

**Comment by tdhopper** [comment]
What's going on here?

**Comment by campos-ddc** [comment]
I'll fix the conflict soon

**Pull request closed without merging**
