### PR TITLE
Keep custom prompts on Windows 

### PR DESCRIPTION
**Pull request by asmeurer**
Fixes https://github.com/conda/conda/issues/1254.

### CODE REVIEW

**Comment by asmeurer** [comment]
This automatically went against the develop branch. I hope that's right.

**Comment by asmeurer** [comment]
I've tested this on my Windows VM and it seems to work.

**Comment by tswicegood** [comment]
Yeah, `develop` is correct for most things -- this is a bugfix PR, though, so I'll merge it straight into `master`.

---

I did test and this all works, so I'll get 2.1.4 out in a few.

**Comment by tswicegood** [comment]
Well, this is merged and released, but the Windows build machines are offline... :sad:

**Comment by tswicegood** [comment]
@ilanschnell can you please build / release tag `v2.1.4` via your build system.

**Comment by ilanschnell** [comment]
Sure.  I'll do it right now.

**Comment by tswicegood** [comment]
Thanks!

**Comment by phobson** [comment]
Wow! thanks so much! this is awesome.

**Pull request merged**
